name = "ProbabilisticCircuits"
uuid = "2396afbe-23d7-11ea-1e05-f1aa98e17a44"
authors = ["Guy Van den Broeck <guyvdb@cs.ucla.edu>"]
version = "0.4.1"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ChowLiuTrees = "be466665-d60c-4e0a-9ae9-070eb5e678a5"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
DirectedAcyclicGraphs = "1e6dae5e-d6e2-422d-9af3-452e7a3785ee"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Lerche = "d42ef402-04e6-4356-9f73-091573ea58dc"
MetaGraphs = "626554b9-1ddb-594c-aa3c-2596fe9399a5"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
TikzGraphs = "b4f28e30-c73f-5eaf-a395-8a9db949a742"

[compat]
CUDA = "3.8.1, 4, 5"
ChowLiuTrees = "0.1.1"
CodecZlib = "0.7"
DirectedAcyclicGraphs = "0.1.3"
Graphs = "1"
Lerche = "0.5"
MetaGraphs = "0.7"
SpecialFunctions = "2.1"
TikzGraphs = "1.3"
julia = "1.6"
